# Generated by Django 3.0.3 on 2020-06-16 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=16, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=32, unique=True)),
                ('email', models.CharField(db_index=True, max_length=64)),
                ('phonenumber', models.CharField(max_length=15)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('rank', models.IntegerField()),
                ('recommendation', models.IntegerField()),
                ('upload_date', models.DateField(db_column='2020-06-16')),
                ('nutrition_document_file_path', models.CharField(max_length=300)),
                ('video_file_path', models.CharField(max_length=300)),
                ('document_file_path', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='FSStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('storage_file_path', models.CharField(max_length=300)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ceo.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Foodstuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodstuff_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('price', models.IntegerField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ceo.Recipe')),
            ],
        ),
    ]
