# Generated by Django 3.0.3 on 2020-06-20 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceo', '0002_auto_20200619_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='fsstorage',
            name='fss_img_file_path',
            field=models.CharField(default='non-img.png', max_length=300),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_img_file_path',
            field=models.CharField(default='non-img.png', max_length=300),
        ),
        migrations.AlterField(
            model_name='account',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='upload_date',
            field=models.DateField(default='2020-06-20'),
        ),
    ]
