# Generated by Django 2.2 on 2020-06-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceo', '0004_auto_20200620_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_img_file_path',
            field=models.ImageField(blank=True, null=True, upload_to='recipe/img/'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recommendation',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='video_file_path',
            field=models.FileField(blank=True, null=True, upload_to='recipe/video/'),
        ),
    ]
