# Generated by Django 2.2 on 2020-06-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceo', '0005_auto_20200620_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='nutrition_document_file_path',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
