# Generated by Django 2.2 on 2020-06-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceo', '0006_auto_20200620_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_kind',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
